CREATE TABLE qweqwe (
`ser` VARCHAR(255) DEFAULT NULL  COMMENT ''

 )  ENGINE=InnoDB AUTO_INCREMENT=107 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
ALTER TABLE t_test modify column name VARCHAR(255) NOT NULL  COMMENT '' ;
ALTER TABLE t_test ADD COLUMN no INT(10)  COMMENT '序号' ;
ALTER TABLE t_test DROP COLUMN remark ;
ALTER TABLE t_test DROP COLUMN time ;
ALTER TABLE test ADD PRIMARY KEY(id);
DROP TABLE shanchu ;
